Use tsc unused variable checking instead of tslint
This was supposed to fix the warning that appears when you try to build:

```
no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
```

Even disabling the rule did not make the warning disappear, but enabling
the checking on tsconfig showed some warnings that this PR removes.
Those are also errors after the upgrade to `react-scripts`, but we can
get the benefits now.

```
ERROR: /home/cfcosta/Projects/go/src/github.com/kiali/kiali-ui/src/components/IstioWizards/WeightedRouting.tsx:161:11 - 'numLocks' is declared but its value is never read.
ERROR: /home/cfcosta/Projects/go/src/github.com/kiali/kiali-ui/src/components/JaegerIntegration/__tests__/LookBack.test.tsx:6:16 - 'onChangeCustom' is declared but its value is never read.
ERROR: /home/cfcosta/Projects/go/src/github.com/kiali/kiali-ui/src/components/JaegerIntegration/__tests__/RightToolbar.test.tsx:6:16 - 'onGraphClick' is declared but its value is never read.
ERROR: /home/cfcosta/Projects/go/src/github.com/kiali/kiali-ui/src/components/JaegerIntegration/__tests__/RightToolbar.test.tsx:6:30 - 'onSummaryClick' is declared but its value is never read.
ERROR: /home/cfcosta/Projects/go/src/github.com/kiali/kiali-ui/src/components/JaegerIntegration/__tests__/RightToolbar.test.tsx:6:46 - 'onMinimapClick' is declared but its value is never read.
```